// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5navHJGi8WoLLK19RcPS3hjoHtbRca6c',
    appId: '1:839712072653:web:3531b19b35636e55e39a84',
    messagingSenderId: '839712072653',
    projectId: 'notification-ba53c',
    authDomain: 'notification-ba53c.firebaseapp.com',
    storageBucket: 'notification-ba53c.firebasestorage.app',
    measurementId: 'G-5192VNG4ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyiAKQHOMGKrG36Fpo41XAsTJahdcLMWk',
    appId: '1:839712072653:android:39fed9cdc70da43ee39a84',
    messagingSenderId: '839712072653',
    projectId: 'notification-ba53c',
    storageBucket: 'notification-ba53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPL5JSJ4kn55TYyIyjFRkOI3_Fmek3RVE',
    appId: '1:839712072653:ios:52c8abf89b979ee7e39a84',
    messagingSenderId: '839712072653',
    projectId: 'notification-ba53c',
    storageBucket: 'notification-ba53c.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPL5JSJ4kn55TYyIyjFRkOI3_Fmek3RVE',
    appId: '1:839712072653:ios:52c8abf89b979ee7e39a84',
    messagingSenderId: '839712072653',
    projectId: 'notification-ba53c',
    storageBucket: 'notification-ba53c.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5P7c-vlZY1RvJZ2-0eXBcUK8g9H7HrJ8',
    appId: '1:839712072653:web:8a0fffef4aaab6f0e39a84',
    messagingSenderId: '839712072653',
    projectId: 'notification-ba53c',
    authDomain: 'notification-ba53c.firebaseapp.com',
    storageBucket: 'notification-ba53c.firebasestorage.app',
    measurementId: 'G-77VHKDLE51',
  );
}
